### PR TITLE
when failures.py runs, map tuples to integer values to avoid copy/com…

### PR DESCRIPTION
**Pull request by jmaher**
…pare of strings. @armenzg r?

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/ouija/197)

### CODE REVIEW

**Comment by armenzg** [comment]
This is overal great. Thanks for tackling this.
My main feedback is around style code changes and explaining a bit more to help future reads of the code.

We can merge after addressing the nits. We can squash and merge to avoid more than one commit.
Let me know if you would need to look at it again or not.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/seta.py, line 14 at r1](https://reviewable.io:443/reviews/mozilla/ouija/197#-KYMujys1PTXEcLwUx9v:-KYMujys893hL3WAETkJ:b-czu4d4) ([raw file](https://github.com/mozilla/ouija/blob/4575cdc6328f0bb4178d41728104fdb95917a839/tools/seta.py#L14)):*
> ```Python
> platforms = []
> buildtypes = []
> testtypes = []
> ```

Please name global variables with upper case.

---

*[tools/seta.py, line 17 at r1](https://reviewable.io:443/reviews/mozilla/ouija/197#-KYMtRYn0_3cXIA2j8tW:-KYMtRYoCBCnxBXV4qSd:b-knjitn) ([raw file](https://github.com/mozilla/ouija/blob/4575cdc6328f0bb4178d41728104fdb95917a839/tools/seta.py#L17)):*
> ```Python
> 
> 
> def map_to_text(index):
> ```

Could you please a sample data and the returning data?
It helps for comprehension.

For instance, later in the code, this function is called with "jobtype" and "value", however, this function's signature says "index" mentally points to an integer.

---

*[tools/seta.py, line 20 at r1](https://reviewable.io:443/reviews/mozilla/ouija/197#-KYMtv6rA-p3FCBoV3w8:-KYMtv6r4hO5TwuFlMbn:buur1jm) ([raw file](https://github.com/mozilla/ouija/blob/4575cdc6328f0bb4178d41728104fdb95917a839/tools/seta.py#L20)):*
> ```Python
>     return [platforms[index & 255],
>             buildtypes[(index >> 8) & 255],
>             testtypes[(index >> 16)]]
> ```

Could you please define some constants at the beginning of the code?
TESTTYPE_BYTE_SHIFT = 16
BUILDTYPE_BYTE_SHIFT = 8
MASK_FIRST_EIGHT_BITS = 255 (is masking the right nomenclature?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/ouija/197#-:-KYMvs4R9H6sTV5oa9dV:b-7d9o31)*

**Comment by jmaher** [comment]
I updated the PR with the feedback.

**Comment by armenzg** [comment]
I'm happy with these changes.

I've made one more:
https://github.com/mozilla/ouija/pull/197/commits/7b84afd1937f8a88e61742860aced42e5e58069d

If you're happy please "squash and merge" from the "merge pull request" button.

Thanks Joel!

**Comment by armenzg** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/ouija/197)*

**Pull request merged**
