### PR TITLE
map job tuples to integers for optimized performance

### PR DESCRIPTION
**Pull request by jmaher**
@armenzg / @MikeLing can you review this? I just need 1 review, so whoever gets to it first :)

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/ouija/196)

### CODE REVIEW

**Comment by MikeLing** [comment]
@jmaher I see multiple commit in this PR, do we need to rebase it first?

**Comment by jmaher** [comment]
possibly, I am not sure how to do that.  there are 4 commits, the first 3
are related to rebaselining and merging my fork- there are zero code
changes there.  The last one has all the changes.

Maybe Armen can walk me through it today in person if there is not an easy
method for fixing this.

**Comment by armenzg** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/failures.py, line 71 at r3](https://reviewable.io:443/reviews/mozilla/ouija/196#-KYLD6q82Ro_B8bZ1TmN:-KYLD6q96cjVYKz0qqzC:bqvwbuz) ([raw file](https://github.com/mozilla/ouija/blob/89f711ab26ea51d68503d94762252dadb06eb7d6/tools/failures.py#L71)):*
> ```Python
>                  (start_date.strftime("%Y-%m-%d"), end_date.strftime("%Y-%m-%d"))
>     try:
>         cache_name = 'seta_cache.json'
> ```

Can we handle the caching logic outside of this function?
```py
if offline:
     if no file:
           data = get_raw_data()
           write cache
     else:
            read file
else:
      normal get_raw_data() path
```

I would like to our methods to be for one purpose rather than multiple (functions versus methods).rein

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/ouija/196)*

**Comment by armenzg** [comment]
When merging the PR we can say "squash and merge".
You can also do it locally with "git rebase -i master". Read [this](https://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit)

**Comment by jmaher** [comment]
hmm, I messed this up

**Pull request closed without merging**
